version: "3.7"
services:
  sciparo:
    build: ../sweet
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres_db
    env_file:
      - .env

  postgres_db:
    image: "postgres:latest"
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 10s
      retries: 5
      timeout: 5s
    volumes:
      - ./trade_hub_dump_v1.0.0.sql:/docker-entrypoint-initdb.d/trade_hub_dump_v1.0.0.sql:ro
    env_file:
      - .env
