spring:
  config:
    #Need to use env file in properties
    import: optional:file:.env[.properties]
  #DB options
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

